### PR TITLE
Update setup_macOS

### PR DESCRIPTION
**Pull request by amjadmajid**
To fix the `ModuleNotFoundError: No module named 'past'` when running the demo

## Title of code changes

- describe the code changes and implications
- add instructions to reproduce if relevant

```python
some code snippets
```

*----------- USE ABOVE FOR FEATURES, BELOW FOR RESULTS -----------*

# Experiment Title

## Abstract

*Briefly describe the experiment and the contribution.*

## Methodology

*Discuss the methods/algorithms used.*

### Reproduction

1. spec file location:
2. git SHA (find this inside the spec file):

Run command: `python run_lab.py <spec file>`

## Result and Discussion

*Provide data in graphs and tables; give explanations and conclusion.*

Data zipfile url (We will send you a Dropbox file request):

### CODE REVIEW

**Review by lgraesser — CHANGES_REQUESTED** [review]
Thanks for fixing this. A cleaner way is just to add the python package 'future' to the pip dependencies in the environment.yml file. Please try that first.

**Comment by kengz** [comment]
Thanks for the report. Could you please provide the full error log when this module `past` is imported? This should not happen since nothing in here is python 2 and we need to see the root cause before approving a solution.

**Comment by mania087** [comment]
Hey I encountered the same problem in Linux environment, the solution that @amjadmajid mentioned solved it. Here is my log when running installation with Docker

> ImportError while loading conftest '/root/SLM-Lab/test/conftest.py'.
test/conftest.py:1: in <module>
    from slm_lab.experiment.control import make_agent_env
slm_lab/experiment/control.py:4: in <module>
    from slm_lab.agent import Agent, Body
slm_lab/agent/__init__.py:7: in <module>
    from torch.utils.tensorboard import SummaryWriter
../miniconda3/envs/lab/lib/python3.7/site-packages/torch/utils/tensorboard/__init__.py:6: in <module>
    from .writer import FileWriter, SummaryWriter  # noqa F401
../miniconda3/envs/lab/lib/python3.7/site-packages/torch/utils/tensorboard/writer.py:18: in <module>
    from ._convert_np import make_np
../miniconda3/envs/lab/lib/python3.7/site-packages/torch/utils/tensorboard/_convert_np.py:12: in <module>
    from caffe2.python import workspace
../miniconda3/envs/lab/lib/python3.7/site-packages/caffe2/python/workspace.py:15: in <module>
    from past.builtins import basestring
E   ModuleNotFoundError: No module named 'past'

**Comment by kengz** [comment]
This has been addressed in #485 . Thanks for the changes!

**Pull request closed without merging**
